..E...
======================================================================
ERROR: test_list_int (__main__.Test03_ModifyContact)
*** Test03 *** GIVEN: filename t99.dat = {'7145551111': ['Steve', 'Jobs'], '5625553333': ['Bill', 'Gates']} AND contacts = Contacts(filename='t99.dat') *** FUNCTION CALL: contacts.modify_contact(id = '7145551111', first_name = 'Richard', last_name = 'Stallman') *** EXPECT: filename t99.dat = {'5625553333': ['Bill', 'Gates'], '7145551111': ['Richard', 'Stallman']} ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elithomas/Documents/CPSC223P/CPSC223P-Lab7/test.py", line 50, in test_list_int
    r = contacts.modify_contact(id = '7145551111', first_name = 'Richard', last_name = 'Stallman')
  File "/home/elithomas/Documents/CPSC223P/CPSC223P-Lab7/contacts.py", line 32, in modify_contact
    self.contact_dict[id] = fullname
NameError: name 'fullname' is not defined

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (errors=1)
